#!/bin/bash
# mutt handler to open attachment with default desktop application.
file="$1"
if [ ! -f "$file" ]; then
	echo "$(basename $0): error - file '$file' does not exist" >&2
	exit 1
fi

tmpdir="/tmp/mutt-xdg-open.$USER";	# fallback
if [ -d /dev/shm ]; then
	# use shm if available since i'm not deleting files. This way they'll
	# be cleaned up at shutdown.
	tmpdir=/dev/shm/mutt-xdg-open.$USER
fi
mkdir -p $tmpdir || exit 1

cp "$file" "$tmpdir" &&
xdg-open "$tmpdir/$(basename $file)"
exit $?
