
[env]
TERM = "xterm-256color"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[scrolling]
history = 8000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
opacity = 1.0

[window.dimensions]
columns = 150
lines = 50

[window.padding]
x = 6
y = 6

[general]
import = [
    "~/.config/alacritty/themes/nord.toml",
]

